### ISSUE TITLE
Dark status icons in dark image preview

### ISSUE THREAD

**Issue by cassidyjames** [b-lam/Resplash#10]
Whoops, another side effect of #5. The status icons in the dark-background image preview thing are dark, meaning they're hard to see.

**Comment by cassidyjames** [comment]
![screenshot_20170409-112152](https://cloud.githubusercontent.com/assets/611168/24839414/0c942f04-1d17-11e7-8506-fc83983bde7d.png)

**Comment by b-lam** [comment]
Fixed in v1.0.3
