### ISSUE TITLE
"Support development" view does not show any donation options

### ISSUE THREAD

**Issue by PacoBell** [b-lam/Resplash#103]
I'd like to support your app financially, but I'm not running Google Play Services and your app apparently breaks without it. Would you mind accommodating users such as myself? Thanks.

**Comment by b-lam** [comment]
Hi @PacoBell! Ya Google doesn't allow apps on the Play Store to have alternative payment methods. Unfortunately that also means that Resplash Pro won't work either. But if you are still interested in sending any money my way, I do have PayPal (https://www.paypal.me/bclam). Thanks for your support!

**Comment by PacoBell** [comment]
Really? Titanium Backup Pro has had a PayPal license key file since forever. Did they get grandfathered or is this an avenue you can investigate?

**Comment by b-lam** [comment]
I definitely think it's against their [policy](https://support.google.com/googleplay/android-developer/answer/9858738):

> Developers offering products within another category of app downloaded on Google Play must use Google Play In-app Billing as the method of payment, except for the following cases:
> - Payment is solely for physical products
> - Payment is for digital content that may be consumed outside of the app itself (e.g. songs that can be played on other music players).

But maybe they just don't care (not something that I would want to risk though)

**Comment by PacoBell** [comment]
Fair enough. Perhaps the Titanium Track folks felt that their license file constituted "digital content" in that it's just a plaintext file that can be read with any text editor.

**Comment by b-lam** [comment]
Ya the only thing I could think of as an alternative would be to set up my own payment server and link it to the app somehow, but I don't think that's a feasible option right now. I'm gonna close this issue in the meantime.
