### ISSUE TITLE
Auto wallpaper changes wallpapers when turned off

### ISSUE THREAD

**Issue by skeleton354** [b-lam/Resplash#105]
My wallpaper keeps changing  when i turn off auto wallpaper. I tried to uninstall it but it still change every 30min. I dont know if there is some timer running in the background but this is really annoing. Can anyone help?

**Comment by b-lam** [comment]
Hi @skeleton354 what version of the app are you on currently?

**Comment by skeleton354** [comment]
Currently 3.1.1

**Comment by b-lam** [comment]
Hmm... that's strange. Is there a possibility that another app is changing the wallpaper? Does the Auto Wallpaper History for Resplash show the wallpaper changes every 30 minutes? Maybe you can try toggling the Auto Wallpaper enable switch on then off again. And as a last ditch effort, perhaps you can try clearing the app data for Resplash, opting into the beta (https://play.google.com/apps/testing/com.b_lam.resplash) and upgrading to v3.2.0.  Let me know how that goes.

**Comment by skeleton354** [comment]
It seems that beta version fixed it. Thanks for your help. If something change i will tell.
