### ISSUE TITLE
More prominent "wallpaper history" screen

### ISSUE THREAD

**Issue by abonhote** [b-lam/Resplash#106]
I'm using the automatic wallpaper history to curate my own wallpaper list. The history page is a bit too far away from the main screen IMHO.

**Comment by b-lam** [comment]
@abonhote There are a couple of things that might help you with this.

1. There is an app shortcut if you hold on the app icon that can bring you directly to Auto Wallpaper settings screen.
2. If you tap on the Auto Wallpaper info notification, you can be brought directly to the detail page for that photo.

**Comment by abonhote** [comment]
Cool, didn't know this. Thanks!
