### ISSUE TITLE
View count

### ISSUE THREAD

**Issue by Thegal** [b-lam/Resplash#112]
it seems that the view count is broken. Some of my photos are losing views while others are gaining them at an extremely fast rate

**Comment by LucidRecords** [comment]
Yah I saw at first I was astonished but I've noticed there's like 6 photos with the same view count and same downloads, my most popular photo when from 560k to 27 views
![Screenshot_20200811-235506](https://user-images.githubusercontent.com/69588865/90022221-20e76800-dc67-11ea-9937-2be444dd67b4.png)

**Comment by b-lam** [comment]
@Thegal @LucidRecords I think this is an Unsplash issue not a Resplash issue. I'm just displaying the data returned from the Unsplash API. It might be helpful to bring this issue up in the Unsplash slack (https://chat.unsplash.com/) to see if they have any info on this.
