### ISSUE TITLE
SearchActivity user tab duplicates photos

### ISSUE THREAD

**Issue by Kenta1561** [b-lam/Resplash#114]
When scrolling through user search results, when a user has less than three images displayed sometimes an image of one user gets added to another user.
In this example when you look closely the photo of the baseball stadium gets added to the third user when scrolling back to the top.

![GIF](https://media.giphy.com/media/fvfR10i62oPu6peeZw/giphy.gif)

**Comment by b-lam** [comment]
Good catch! I just pushed up a change that should fix this.
