### ISSUE TITLE
New Suggestions

### ISSUE THREAD

**Issue by RadheShyamDasa** [b-lam/Resplash#117]
Please add an option - auto change wall each time when unlocked and also add ability to choose the auto walls from liked photos...this is the only only stopping me from paying for pro.

**Comment by b-lam** [comment]
Hey @kkrrssnnaa, thanks for the suggestions! Unfortunately I don’t think either of these are really possible. For auto changing wallpaper each time the device is unlocked, I don't think Android will reliably allow apps to detect when the device is unlocked (for example if the app is killed by the user or OS). Auto Wallpaper from liked photos is a restriction from Unsplash as they do not allow random photo selection from a user's liked photos (you could create a collection with your liked photos though). I really would like to add these but I don't think it's currently possible :(

**Comment by kkrrssnnaa** [comment]
@b-lam the later one is okay, but there are few apps which use this feature...auto change when unlocked.

Is it possible,  atleast to let the user enter the number of minutes for auto change? Like 1 min to 48 hours or so? It would be even better.

**Comment by b-lam** [comment]
Hmm let me know which apps can do it and I'll take a look into what they might be doing (it is possible but the reliability/battery efficiency is what I'm concerned about). Resplash uses an Android feature called `WorkManager` which allows the app to schedule background tasks like auto wallpaper in a battery efficient way. One of the limitations of `WorkManager` is that has a minimum time interval of 15 minutes. I could use an `AlarmManager` to schedule tasks at a lower and more precise interval but it will not be very battery efficient. It's not impossible to add but adding the complexity of having to explain to other user's the trade-offs in the app is definitely a challenge. Let me know what you think.

**Comment by kkrrssnnaa** [comment]
@b-lam i'll mention them, rn I don't have them. Oh, okay...understood. But do think about it, it would be great to set it for as low as possible.

**Comment by kkrrssnnaa** [comment]
@b-lam what does the search term option does?

**Comment by b-lam** [comment]
> @b-lam what does the search term option does?

@kkrrssnnaa You will get photos from Auto Wallpaper that match that search term. For example: mountains, dogs, cars

**Comment by kkrrssnnaa** [comment]
> > @b-lam what does the search term option does?
> 
> @kkrrssnnaa You will get photos from Auto Wallpaper that match that search term. For example: mountains, dogs, cars

I haven't bought pro rn, does it mean that I can put something and then it'll fetch walls from that term?

**Comment by b-lam** [comment]
@kkrrssnnaa Using the search term for Auto Wallpaper is currently a pro feature but yes you can put as many search terms as you want

**Comment by kkrrssnnaa** [comment]
Can you add pexels also? Is it possible @b-lam ?

**Comment by b-lam** [comment]
@kkrrssnnaa Adding pexels would technically be possible but I feel like it would have to be a completely new app otherwise it would be a little confusing for users. It would be like if Instagram just started adding images from Unsplash.

**Comment by kkrrssnnaa** [comment]
Ah, yes. I thought it would be even bigger library for walls and photos, and pexels also supports videos.
Anyways, looking forward for exciting updates 🥳

**Comment by kkrrssnnaa** [comment]
After a while the walls are repeating...using search terms... @b-lam

**Comment by b-lam** [comment]
@kkrrssnnaa What search terms are you using? It really depends on how many photos come up for a certain search term. If there are only 5 photos returned for a certain term then you are likely going to get some repeats.

**Comment by kkrrssnnaa** [comment]
@b-lam 
```
nature, mountains, panorama, panoramic, space, vrindavan, yamuna, panoramic 
```

**Comment by b-lam** [comment]
@kkrrssnnaa So it looks like vrindavan and yamuna don't have that many photos for those search terms which most likely explains the duplicates.

**Comment by kkrrssnnaa** [comment]
That is okay but sometimes even the other walls appear same like...mountains/space

**Comment by kkrrssnnaa** [comment]
Hey @b-lam I think there is some glitch...the app shows too many picture s of moon now. Repeat and new both. I don't even have any related term in search...still it shows moon always.

I removed that search term a while ago, but it just keeps on going on moon.

**Comment by kkrrssnnaa** [comment]
> Hey @b-lam I think there is some glitch...the app shows too many picture s of moon now. Repeat and new both. I don't even have any related term in search...still it shows moon always.
> 
> I removed that search term a while ago, but it just keeps on going on moon.

@b-lam can you change my payment mail? I bought from amayjainbusiness@gmail.com and I want to move it to amayjain79@gmail.com

**Comment by b-lam** [comment]
@RadheShyamDasa Sorry for the late reply! Unfortunately it's not possible to change the payment email. All payments are handled by Google, the only thing I can do from my side is issue refunds so I can do that if you want to repurchase through your other email. As for the "moon glitch", I can't be 100% certain of the cause but the system is random and if there are a lot of moon photos that get returned when searching for space (or anything else), there is going to be a high chance of getting that kind of image. You can try clearing the app data to reset things but I don't think that is the issue.

**Comment by RadheShyamDasa** [comment]
> @RadheShyamDasa Sorry for the late reply! Unfortunately it's not possible to change the payment email. All payments are handled by Google, the only thing I can do from my side is issue refunds so I can do that if you want to repurchase through your other email. As for the "moon glitch", I can't be 100% certain of the cause but the system is random and if there are a lot of moon photos that get returned when searching for space (or anything else), there is going to be a high chance of getting that kind of image. You can try clearing the app data to reset things but I don't think that is the issue.


Sure, please issue a refund.
