### ISSUE TITLE
Collection as Autowallpaper not working

### ISSUE THREAD

**Issue by josenoel1980** [b-lam/Resplash#119]
Under Auto wallpaper collection is selected as source and one collection added,but auto wallpaper displays random pictures instead of pictures from collection.

Note:pro version

**Comment by josenoel1980** [comment]
Its working from today

**Comment by josenoel1980** [comment]
Looks like unsplash.com issue.Its working as expected now

**Comment by b-lam** [comment]
Thanks for the update Jose! Yeah I think Unsplash was having a bunch of issue with collections a few days ago. This and not being able to add photos to collections. Hopefully they can improve the stability.
