### ISSUE TITLE
Wrong spelling for a class name!

### ISSUE THREAD

**Issue by KaustubhPatange** [b-lam/Resplash#120]
Your `BaseDataSource` class file name is `BaseDataSouce` you missed out `r`.

I noticed it when I want to `find All` class files that ends-with `Source` & it didn't list out. It's not a big issue but looks a bit odd when navigating through code.

I could've submitted a PR regarding this but the ongoing issues about spamming Github repositories I stopped & created this issue so that you can resolve it yourself. All you have to do is change the file name that's it!

BTW, amazing level of abstraction in your code I learned a lot from this repository. Cheers :)

**Comment by b-lam** [comment]
Whoops! Good catch, I'll fix it someday when I have free time. Glad to hear that you were able to learn something from my code 😄
