### ISSUE TITLE
Own collections: expected an int at path  $[0].id

### ISSUE THREAD

**Issue by abonhote** [b-lam/Resplash#130]
When I try to open my own collections, it says:

`Uh oh...
error: d.g.a.q: Expected an int but was 47oSOx_Ec2s at $[0].id`

All I did was trying to create a new collection from the "add to collection"-dialog (tag icon), tapping on the +.

**Comment by abonhote** [comment]
I solved this by deleting some corrupted collections on unsplash. Maybe it's their fault...

**Comment by b-lam** [comment]
Hey @abonhote, thanks for pointing this out! It looks like Unsplash changed collection ids from integers to strings without updating their documentation or notifying any of the developers using the API 🤦 . I'll try to fix this soon.
