### ISSUE TITLE
Add the ability to use users' likes as a collection source

### ISSUE THREAD

**Issue by AKPWebDesign** [b-lam/Resplash#139]
It would be really nice if I could use my own likes, or someone else's likes, as a collection source.

I tried adding https://unsplash.com/@akp/likes as a collection URL manually, but I am shown a message stating that the URL is invalid.

**Comment by b-lam** [comment]
Hey Austin, unfortunately Unsplash's API doesn't have the option to use a user's likes as a parameter for getting a random photo (https://unsplash.com/documentation#get-a-random-photo). The best alternative right now is to create a collection that contains all your liked photos.

**Comment by AKPWebDesign** [comment]
Hey Brandon, thanks for the reply! I know that the Unsplash Source API (https://source.unsplash.com/) does support grabbing from a user's likes, but I'm sure that if you've implemented everything with their other API, adding that functionality in might be a pain. In the meantime, I probably will just create my own collection, that seems simple enough.

**Comment by b-lam** [comment]
Yeah I'm surprised that the option isn't available in the full API and implementing the source API is kinda hacky and isn't that simple and might go against some API guidelines. If they every add the option to the full API, I'll definitely add it to Resplash but until then hopefully the collection solution work well enough.
