### ISSUE TITLE
"Login" not working

### ISSUE THREAD

**Issue by D1M0NW1NN3R** [b-lam/Resplash#141]
Switched to a Xiaomi Redmi Note 10 Pro recently and found out the "login" button isn't working (I press and nothing happens). Everything worked perfectly on Redmi Note 7, wonder if I'm the one who has this issue.

Android 11
MIUI Global 12.5.4

**Comment by b-lam** [comment]
Hey @D1M0NW1NN3R, sorry to hear that you are encountering this issue. Do you have Google Chrome installed on your new phone? Resplash uses an Android feature called custom tabs that requires Google Chrome to be installed. Let me know if login works after installing Chrome 🙂

**Comment by D1M0NW1NN3R** [comment]
Yeah, it really works now. Thanks a lot. I'm just wondering why it performed good on my Note 7 without Chrome.
_________
And thank you really much for all the work you do, your app is incredible, already made you a donation.

**Comment by b-lam** [comment]
@D1M0NW1NN3R I think there are some other browsers other than Chrome that support custom tabs so it's possible that you had one of those installed but glad that it worked out. One of these days I'll try and add a backup solution for people who don't have Chrome installed.
