### ISSUE TITLE
Auto Wallpapers, where are those saved on the device? I want to clear/delete them to save storage.

### ISSUE THREAD

**Issue by vrindavan** [b-lam/Resplash#143]

**Comment by b-lam** [comment]
Hey @vrindavan, auto wallpapers are not saved on the device, they are applied directly as wallpaper. You can clear the app cache the way you normally would for any app if you want to save storage, there is also a button in the app settings to do that. I hope that helps.

**Comment by vrindavan** [comment]
@b-lam so after wallpaper is changed it is no longer taking any space on the device?

**Comment by b-lam** [comment]
@vrindavan yup auto wallpaper doesn't save anything on the device
