### ISSUE TITLE
Remove trackers

### ISSUE THREAD

**Issue by yesNOmaybe69420pogchamp69** [b-lam/Resplash#144]
Can you remove trackers please?

**Comment by b-lam** [comment]
Hey @yesNOmaybe69420pogchamp69 what trackers are you referring to?

**Comment by yesNOmaybe69420pogchamp69** [comment]
> what trackers are you referring ![to?](https://a.tmp.ninja/lBmpGVoO.jpg)
These ones

**Comment by b-lam** [comment]
Sorry I don't think I can remove Firebase from the app. Firebase provides useful features and info that help make Resplash a lot better. All of the code for Resplash is available on Github so if you want to set up your own build without Firebase that is totally possible.

**Comment by yesNOmaybe69420pogchamp69** [comment]
> Sorry I don't think I can remove Firebase from the app. Firebase provides useful features and info that help make Resplash a lot better. All of the code for Resplash is available on Github so if you want to set up your own build without Firebase that is totally possible.
What data does it provide?

**Comment by b-lam** [comment]
@yesNOmaybe69420pogchamp69 The main feature that Firebase provides is Crashlytics which helps me monitor and fix bugs/crashes that come up when users are using the app.

**Comment by yesNOmaybe69420pogchamp69** [comment]
Ok
