### ISSUE TITLE
Could you share the location of the Cache Files?

### ISSUE THREAD

**Issue by terryl213** [b-lam/Resplash#169]
Hi, @b-lam, 

May I know the actual Cache files location of the Resplash as I couldn't find it under Android\data folder?

Thanks a lot.

**Comment by b-lam** [comment]
@terryl213 There isn't a public cache directory for Resplash however the internal app cache should be located in `/data/data/com.b_lam.resplash\cache`

**Comment by terryl213** [comment]
Thank you, @b-lam.
