### ISSUE TITLE
Picture don't save in Gallery (Android)

### ISSUE THREAD

**Issue by eSebbie** [b-lam/Resplash#23]
Hi,

I found a bug with downloading photos in the collection. I find the solution to the issue, the reason why photos aren't appearing in Gallery is because images are downloaded as .JPEG, if you would rename the file to .jpg the picture would appear in Gallery.

Just wanted to point that out.

Thanks,
Seb

**Comment by b-lam** [comment]
Images should now be saved as .jpg in version 1.0.8
