### ISSUE TITLE
Disable/Remove navigation draw?

### ISSUE THREAD

**Issue by harunarrosyid** [b-lam/Resplash#31]
help me for remove a navigation drawer, i no need navigation draw because i already move all item from navigation draw to menu.

**Comment by b-lam** [comment]
@harunarrosyid The navigation drawer was implemented using [MaterialDrawer](https://github.com/mikepenz/MaterialDrawer) in the MainActivity onCreate() so just remove that code. Since this is not an issue with Resplash I'm going to close this issue.
