### ISSUE TITLE
How to change set layout?

### ISSUE THREAD

**Issue by harunarrosyid** [b-lam/Resplash#32]
I want to change default_layout set to grid or grid layout only, i already try change to string.xml from list to grid but layout not move to grid

![untitled](https://user-images.githubusercontent.com/33005248/32818728-8338bb6a-c9f7-11e7-81d4-c9450d0158f6.png)

**Comment by b-lam** [comment]
@harunarrosyid Preferences are defined in the preferences.xml and are loaded from SharedPreferences in each of the image fragments.

**Comment by harunarrosyid** [comment]
@b-lam thanks for answer, I already change in prefences to grid but no move to grid?

**Comment by b-lam** [comment]
@harunarrosyid It is possible that the SharedPreference is loading the backup default in the image fragments for example in FeaturedFragment "String mLayoutType = sharedPreferences.getString("item_layout", "List");" But it is hard to say because I'm not sure what else you have changed/not changed.

**Comment by harunarrosyid** [comment]
@b-lam do you give me solution or alternate?

**Comment by b-lam** [comment]
@harunarrosyid I'm just suggesting potential parts in the code that have to do with controlling layout. I cannot really give you a definite solution without seeing/testing your code.

**Comment by harunarrosyid** [comment]
@b-lam ok thanks for you :)
