### ISSUE TITLE
Better "download management"

### ISSUE THREAD

**Issue by peterbonge** [b-lam/Resplash#44]
This app is really great, but I have a little problem with the "download management". If I want to set a photo as the wallpaper I'm often trying different positions and it seems that the app is downloading the photo again and again. Also, after doing this, I have several copies of this photo in the download folder.

So instead of always re-downloading and re-saving the same photo it would be nice if the app would detect an already downloaded photo and offer options like:

- Use the already downloaded copy
- Re-download the photo (and overwrite the copy instead of making a new one)

**Comment by b-lam** [comment]
@peterbonge Hmm.. there was a reason that I set it up this way but I can't remember why at the moment. Although what you are saying makes sense and I'll probably add these changes into the next update.
