### ISSUE TITLE
Use the release in github to contain the apks

### ISSUE THREAD

**Issue by gaara87** [b-lam/Resplash#45]
I see that all the apks have been going into the commit history along with its source code. You should check this out https://help.github.com/articles/creating-releases/

**Comment by b-lam** [comment]
Yup this is something that I've actually been doing https://github.com/b-lam/Resplash/releases but I've been commiting it too. Is there any reason that this shouldn't be done other than it being redundant?

**Comment by gaara87** [comment]
Git pull becomes much larger?

**Comment by b-lam** [comment]
Yup that's fair, I'll take them out in the future.
