### ISSUE TITLE
Use LightStatusBar for dark icons

### ISSUE THREAD

**Issue by cassidyjames** [b-lam/Resplash#5]
Since the app is very light and uses a light status bar, you can use the android:windowLightStatusBar theme attribute or set `View.setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_‌​BAR);` to get dark icons on the status bar. This is what Google is doing with apps like Allo and the new settings UI in Android O.

**Comment by b-lam** [comment]
Sounds like a good idea! I've made the change so hopefully the update should be available soon.

**Comment by cassidyjames** [comment]
Dude. Awesome. By the way, your app is rad. :wink:

**Comment by b-lam** [comment]
@cassidyjames Thanks! Glad to hear that you're enjoying the app. Hopefully I'll have more time to work on it once I'm done my exams. (Big fan of elementary btw)
