### ISSUE TITLE
怎么定义的？

### ISSUE THREAD

**Issue by live17909** [b-lam/Resplash#51]
buildConfigField("String", "RELEASE_APP_ID_1", RELEASE_APP_ID_1)
        buildConfigField("String", "RELEASE_SECRET_1", RELEASE_SECRET_1)
        buildConfigField("String", "RELEASE_APP_ID_2", RELEASE_APP_ID_2)
        buildConfigField("String", "RELEASE_SECRET_2", RELEASE_SECRET_2)
        buildConfigField("String", "DEV_APP_ID", DEV_APP_ID)
        buildConfigField("String", "DEV_SECRET", DEV_SECRET)
        buildConfigField("String", "GOOGLE_PLAY_LICENSE_KEY", GOOGLE_PLAY_LICENSE_KEY)

？

**Comment by b-lam** [comment]
You have to define them in a gradle.properties file
