### ISSUE TITLE
v1.3.2 APK unsigned?

### ISSUE THREAD

**Issue by IzzySoft** [b-lam/Resplash#57]
The APK attached to the v1.3.2 release seems to lack certificates:

    $ apksigner verify resplash_1.3.2.apk
    ERROR: No signing certificates found in resplash_1.3.2.apk

Could you please replace the file by a fixed APK? Thanks!

**Comment by b-lam** [comment]
@IzzySoft Thanks for letting me know. Android Studio has been having some issues recently with signing APKs. The file should be fixed now.

**Comment by IzzySoft** [comment]
Thanks for the fast reply! And I can confirm the new APK being fine :+1:
