### ISSUE TITLE
Can't download

### ISSUE THREAD

**Issue by rollerpiggy** [b-lam/Resplash#61]
I use an Android 8.1 and I just can't download any pics, usually when I press "download" it tells me that the download started and then I got a message that it faild. I just can't download anything.

**Comment by b-lam** [comment]
Hey @rollerpiggy! I have a couple of questions:

1. Do downloads from Chrome work?
2. Have you tried clearing the cache/data from the download manager?
3. Have you tried restarting your phone?
4. Can you provide screenshots of the error if the things above don't work?

Thanks!

**Comment by rollerpiggy** [comment]
Hey, thanks for answering!
I restarted my phone and cleaned the cache, still nothing. I'm gonna send
you some screenshots.

However, downloads with chrome does work, but I wanted to do it through the
app since it's much more intuitive and easy.

I don't know if that has anything do do with it but I am from Brazil so
maybe the location would be some problem? I don't know.

Em sex, 22 de fev de 2019 22:39, Brandon Lam <notifications@github.com>
escreveu:

**Comment by b-lam** [comment]
@rollerpiggy I've recently rewritten the entire app including the downloader. Let me know if you are still experiencing this issue on v3.0.0
