### ISSUE TITLE
[feature request] widget to refresh wallpaper

### ISSUE THREAD

**Issue by cstayyab** [b-lam/Resplash#63]
I have seen the auto-wallpaper feature and it works perfectly, but sometimes I don't like a wallpaper and want to change it instanty for that I have to open app and go to auto-wallpaper section and then tap 'Refesh Wallpaper' button. 
I want to simplify this process by adding a button widget that can be placed on home screen and tapping it will change wallpaper instantly.

I hope this will be a nice addition to app.

**Comment by ongmk** [comment]
Or an app action would do the same trick.

**Comment by b-lam** [comment]
Hey @cstayyab @ongmk I'm going to add a quick settings tile so that you can change it the wallpaper from the notification drawer. It will be available in the next update 😄

**Comment by b-lam** [comment]
Rolling this out now in v2.0.0
