### ISSUE TITLE
Auto wallpaper

### ISSUE THREAD

**Issue by BasemSenousy** [b-lam/Resplash#64]
I hope you can add an easy way to choose which images we want to display only not by typing a name maybe by clicking the image we want in app or upload from folder in mobile storage or both 
Also I found that I must open the Resplash app to make the wallpaper change I choose to wallpaper change every 15 minutes but it's not changing
I turned off all conditions so I don't know if I have to turn on Idle or off to make it change by itself
Thank you and I really hope you apply my advice

**Comment by b-lam** [comment]
@BasemSenousy Choosing the photos for Auto Wallpaper is available in v3.0.0. As for changing every 15 minutes, you should disable battery optimizations for Resplash so that it is allowed to run in the background more frequently.
