### ISSUE TITLE
Auto wallpaper source - liked?

### ISSUE THREAD

**Issue by timetotom** [b-lam/Resplash#72]
Hi Brandon, app is fantastic - functional, clean and the ability to navigate via account login is great.

Is there any chance of setting the auto wallpaper source as account 'liked' photos or even a specific collection? This would make it perfect. Cheers mate

**Comment by gutobernardo** [comment]
I came here to request this same feature. There are some collections with the exact mood I want, so it's less random than a broader tag. Loving the app by the way!

**Comment by b-lam** [comment]
Auto Wallpaper can now be set to use specific collections, users or search terms in v3.0.0
