### ISSUE TITLE
Add Hungary Language

### ISSUE THREAD

**Issue by Axhyre** [b-lam/Resplash#75]
Translates : 
NEW - ÚJ
FEATURED - FELKAPOTT
COLLECTIONS - GYŰJTEMÉNYEK
LATEST - LEGÚJABB
OLDEST - LEGRÉGEBBI
POPURAL - FELKAPOTT
FREE HIGH RESOLUTION PHOTOS - INGYENES JÓ MINŐSÉGŰ FOTÓK
AUTO WALLPAPER - AUTOMATIKUS HÁTTÉRKÉP
SUPPORT DEVELOPMENT - TÁMOGATÁS
SETTINGS - BEÁLLÍTÁSOK
ABOUT - NÉVJEGY
COFEE - KÁVÉ
KEEPS ME AWAKE THROUGHT THE LATE NIGHT SESSIONS - SEGÍT FENTMARADNI A KÉSŐ ESTI KÓDOLÁSBAN
SOMETIMES I NEED TO EAT SOMETHING HEALTHY - NÉHA ENNEM KELL VALAMK EGÉSZSÉGESET
EVERYONE LIKES PIZZA - MINDENKI SZERETI A PIZZÁT
FANCY MEAL - SZÉP MENÜ
GONNA TREAT YOURSELF ONCE IN A WHILE - EGYSZER MÁST IS KELL ENNEM
GENERAL - ÁLTALÁNOS
LANGUAGE - NYELV
THEME - TÉMA
CUSTOM API KEY - SAJÁT API KULCS
CLEAR CACHE - MARADVÁNYOK TÖRLÉSE
CACHE SIZE - MARADVÁNYOK MÉRETE
QUALITY - MINŐSÉG
LOAD QUALITY - BETÖLTÉSI MINŐSÉG
CHOOSE THE QUALITY OF THE IMAGES THAT ARE LOADED - VÁLASZD KI A MINŐSÉGÉT A BETÖLTÖTT KÉPEKNEK
DOWNLOAD QUALITY - LETÖLTÉSI MINŐSÉG
CHOOSE THE QUALITY OF THE IMAGES THAT ARE DOWNLOADED - VÁLASZD KI A MINŐSÉGÉT A LETÖLTÖTT KÉPEKNEK
WALLPAPER QUALITY - HÁTTÉRKÉP MINŐSÉGE 
CHOOSE THE QUALITY OF THE WALLPAPERS SET - VÁLASZD KI A BEÁLLÍTOTT HÁTTÉRKÉPEK MINŐSÉGÉT
LAYOUT - MEGJELENÉS
CHOOSE LAYOUT - VÁLASZ MEGJELENÉST
CHOOSE IMAGES HOW DISPLAYED - VÁLASZD KI HOGYAN LEGYENEK MEGJELENÍTVE A KÉPEK
OTHER - EGYÉB
GO TO UNSPLASH.COM - WEBOLDAL MEGNYITÁSA
INTRODUTION - BEMUTATKOZÁS

**Comment by Axhyre** [comment]
This is not the full translations i send the others soon

**Comment by b-lam** [comment]
@Axhyre Awesome! Translations are always welcome :) All you need to do is translate the strings in this file https://github.com/b-lam/Resplash/blob/master/app/src/main/res/values/strings.xml Feel free to skip any string that you don't think needs translating. It would be great if you could keep it in the xml format. Let me know if you have any questions.

**Comment by Axhyre** [comment]
I do it soon

**Comment by b-lam** [comment]
@Axhyre I don't think I have heard back from you recently. Let me know if you are still interested in translating.
