### ISSUE TITLE
Auto closes After splash

### ISSUE THREAD

**Issue by naveedhassan913** [b-lam/Resplash#79]
When App is opened it automatically exits after splash screen, no idea..if there is detection for root or patching tools. V1.2.2 is working.. Hope you will fix

_Sent from my HOT 4 PRO using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by b-lam** [comment]
Hi @naveedhassan913, I'm not sure if you have tried the app recently. Let me know if this issue is still occuring for you on the latest version.
