### ISSUE TITLE
Double Tap to change wallpaper functionality

### ISSUE THREAD

**Issue by stastsoy** [b-lam/Resplash#84]
A user can double tap on the screen to change a wallpaper. 
Please see this app with this functionality: https://play.google.com/store/apps/details?id=hd.uhd.wallpapers.best.quality

Thanks,
Stas

**Comment by abonhote** [comment]
I second this if not implemented as live wallpaper. Maybe a shortcut triggered by a launcher gesture could do the job.

**Comment by b-lam** [comment]
@abonhote If you want to use Resplash with as a live wallpapers I would recommend using Muzei which has a double tap to change option. There is also a widget that can change the wallpaper for Auto Wallpaper in the latest version (v.3.2.0). I hope that helps.

**Comment by abonhote** [comment]
@b-lam you misread my sentence - I don't like LWPs, especially when there are other ways to achieve the same thing. Resplash is perfectly fine.

**Comment by b-lam** [comment]
@abonhote Sorry I misunderstood what you were saying. What did you mean why "shortcut" and "launcher gesture" because I don't think there is any universal way to do that without using live wallpapers.

**Comment by abonhote** [comment]
I don't know how this works technically, but my launcher (smart launcher) and others like Nova offer gestures like double tap. You can assign actions (intents?) to a gesture, like directly call a person, create a new note in evernote, open a WhatsApp group chat and stuff like this.

**Comment by abonhote** [comment]
![Screenshot_20200714-233048](https://user-images.githubusercontent.com/264473/87478470-1e72fd80-c62a-11ea-9f56-57c41c30e00a.jpg)

Smart Launcher gesture shortcut screen

**Comment by b-lam** [comment]
@abonhote Okay I see what you mean now. So without getting too technical, what you might notice about all those actions are that they are set to open a screen within the app. They can't actually perform actions without opening a screen within the app. Hence why I made a quick settings button and a widget for Auto Wallpaper. I hope that makes sense.

**Comment by abonhote** [comment]
@b-lam I really believe it's possible to tell an app to do something without opening a screen. My Android dev skills aren't very well developed, but I know that apps like Tasker are able to send/receive signals to/from other apps. I am turning off my FairEmail office account during holidays that way, by sending an intent:

> You can automatically send commands with for example Tasker:
> New task: Something recognizable, Action Category: Misc/Send Intent, Action: eu.faircode.email.ENABLE, Target: Service

Found here: https://github.com/M66B/FairEmail/blob/master/FAQ.md

Don't get me wrong, I don't need that functionality - who needs wallpapers anyway? - but it's an interesting concept :-)

**Comment by b-lam** [comment]
@abonhote I 100% agree, it is possible to tell an app to do something without opening it and that would be done through intents. However what you are describing with Smart Launcher/Nova launcher are app shortcuts (https://developer.android.com/guide/topics/ui/shortcuts) which do use intents but according to the documentation, they need to be intents that open screens in your app. I could add a Tasker plugin that changes the wallpaper (similar to what Muzei does) but with regards to specifically "changing the wallpaper when double tapping the home screen", I think it needs to be done using a live wallpaper.
