### ISSUE TITLE
Crashing download

### ISSUE THREAD

**Issue by tychoregter** [b-lam/Resplash#86]
Hey man, I just updated the app from the Google Play store, I found a nice wallpaper but unfortunately the app crashed when I tried to download it, cleared my cache and stuff but it didn't fix it.

**Comment by b-lam** [comment]
Hey @tychoregter, thanks for letting me know about this! Unfortunately this is a problem caused by Android 9 but I am going to roll out an update later today that should temporarily fix this.

**Comment by tychoregter** [comment]
Hey @b-lam I'm using a OnePlus 7 Pro on Q, not Pie. Is that the same issue or something else?

**Comment by b-lam** [comment]
@tychoregter Whoops, I meant to say Android 10/Q not Android 9. The update is ramping now so hopefully it will be available to you soon.

**Comment by tychoregter** [comment]
@b-lam I just updated a second ago and it's working fine again! Thanks for the quick work!
