### ISSUE TITLE
Feature request, have the 'auto wallpaper Next' button on the front page so it's less clicks away

### ISSUE THREAD

**Issue by aidandavis** [b-lam/Resplash#88]
I use this exclusively for daily wallpapers. I occasionally cycle through a few if there's ones I don't like or don't go well behind app icons on the home page.
It would be great to have the Next Wallpaper button on the home page of the app if auto wallpaper is turned on.

**Comment by b-lam** [comment]
Hi Aidan, currently there is a quick settings tile that can be added to your notification drawer that will skip the current wallpaper. Let me know if that works for you or if you need any help enabling it 😊

**Comment by aidandavis** [comment]
That's great! I didn't realise. Thanks for your help.
