### ISSUE TITLE
Light navbar icons on light background

### ISSUE THREAD

**Issue by cassidyjames** [b-lam/Resplash#9]
Looks like a side effect of #5. The _nav bar_ is now white-on-white in Android 7.1. I think dark nav bar buttons only works on Android O, so might have to do the dark status bar icons differently?

**Comment by cassidyjames** [comment]
![screenshot_20170409-111131](https://cloud.githubusercontent.com/assets/611168/24839351/b7c6d7d4-1d15-11e7-942f-216ccbf703e1.png)

**Comment by b-lam** [comment]
Hmm... Interesting... I'll into it in a couple of days. I might just go with a black or transparent nav bar instead.

**Comment by cassidyjames** [comment]
:+1:

**Comment by b-lam** [comment]
Fixed in v1.0.3
