### ISSUE TITLE
Bug. Auto wallpapers changer not working 

### ISSUE THREAD

**Issue by christubuntu** [b-lam/Resplash#92]
Worked a few times but stopped. Now I need to change manually. Device= Galaxy Note 9, Android 10. The app is not optimized in battery settings.

**Comment by b-lam** [comment]
Hi @christubuntu, I'm not sure if you have tried the app recently or have tried any of the tips listed here https://dontkillmyapp.com/samsung but any problems that you experienced should be solved. Let me know how it goes.
