### ISSUE TITLE
Add option for horizontal wallpaper fix

### ISSUE THREAD

**Issue by SiddharthJadav** [b-lam/Resplash#95]
Add an option for horizontal wallpaper fix for launchers like Pixel launcher where the wallpaper is not centered if more than 1 pages are present.

**Comment by b-lam** [comment]
Added in v3.0.0

**Comment by SiddharthJadav** [comment]
Hi. Thanks for acknowledging. I tried the feature but it's a crop rather than the actual shift. Is it possible to get centered wallpaper without cropping?

**Comment by b-lam** [comment]
@SiddharthJadav Unfortunately I don't think it is possible, if you know of any apps that can do this let me know and I'll investigate.

**Comment by SiddharthJadav** [comment]
Hi. The app called Walpy does this. 

https://play.google.com/store/apps/details?id=com.feresr.walpy

**Comment by b-lam** [comment]
@SiddharthJadav Hmm, that's strange. For me when I enabled the horizontal fix on Walpy it cropped but when I disabled it, it shifts. I can investigate but I'm not exactly sure what they are doing in code.

**Comment by b-lam** [comment]
@SiddharthJadav I figured it out and added the option in v3.2.0

**Comment by SiddharthJadav** [comment]
Thanks for all the effort @b-lam .
