### ISSUE TITLE
[Feature Request] Muzei Support

### ISSUE THREAD

**Issue by leoherzog** [b-lam/Resplash#98]
Love the 3.0 rewrite, auto wallpaper is great! Would you consider adding support for [Muzei](https://github.com/romannurik/muzei/)?

**Comment by b-lam** [comment]
@leoherzog I can definitely consider it. Is there any specific feature from Muzei that you would like to see in Auto Wallpaper instead?

**Comment by leoherzog** [comment]
I love Muzei's automatic blurring and darkening of the image, the double-tap to un-blur while on the homescreen launcher, and the ability to open Muzei to see metadata about the current photo.

**Comment by b-lam** [comment]
Cool, I'm probably going to try and add blurring and other filtering options to Auto Wallpaper but can also look into adding Muzei support too.

**Comment by b-lam** [comment]
Hey @leoherzog, would you be interested in testing a build with Muzei support and giving me some feedback?

**Comment by leoherzog** [comment]
Absolutely! Just tell me what you need from me.

**Comment by b-lam** [comment]
Cool! Click on this link (https://appdistribution.firebase.dev/i/3c2805704f2ae8f7) to join the testing channel and you should get an email with instructions (This is my first time using this distribution method so I'm not 100% sure how it works).

**Comment by leoherzog** [comment]
Couldn't do an install in place, but I did an uninstall and install from Firebase. Looks good so far! Perhaps consider having the title be "Untitled" instead of an empty string if there isn't one?

**Comment by b-lam** [comment]
Yup I kinda expected that to be the case, unfortunately the keys that I use to sign my apks aren't the same as the ones that get used when the app comes from the Play Store. So this probably means that you should reinstall the one from the Play Store once you are done testing to ensure that you get future updates. I've added the "Untitled" change. Hopefully I should be able to get this out in the next few days.

**Comment by leoherzog** [comment]
Pro purchased! Thanks for being an awesome dev!

**Comment by b-lam** [comment]
Awesome, thanks for your support! ❤️

**Comment by b-lam** [comment]
Added in v3.1.0. Rolling out to beta testers on Google Play now. 🎉
